### ISSUE TITLE
Syntax snippet for extern-singleton-function omits "function"

### ISSUE THREAD

**Issue by FriedrichGretz** [boschresearch/blech-tools#4]
**Describe the bug**
Expand syntax snippet for extern-singleton-function in the IDE. You get
```
@[CFunction (binding = "<c-function macro>", header = "<C header>.h")]
extern singleton <name> (<inputs>) (<outputs>) returns <type>
```
The keyword `function` is missing.

**Comment by schorg** [comment]
Fixed with commit c83d27ad294dc3a8779011605da23244e0247b6a .
