### ISSUE TITLE
Gracefully deal with unimplemented language elements.

### ISSUE THREAD

**Issue by FriedrichGretz** [boschresearch/blech-tools#5]
**Is your feature request related to a problem? Please describe.**
Whenever the language server encounters a language element that has not yet been implemented it simply crashes, forwarding the compiler's error message.

For example: 
```
Exception in language server Print, Assert, Assume not implemented yet.
```

**Describe the solution you'd like**
Display this issue like any other expected syntax error.

**Comment by schorg** [comment]
`failwith` is no longer used in the blech compiler to report unsupported language features.
See commit https://github.com/boschresearch/blech/commit/fb65953de51d46ac5b0432a09c876e3bf433488c
